In [109]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torchvision.models import resnet18
from torch.utils.data import DataLoader
model = torch.load('./models/modelLeNet.pth')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
batch_size = 8
device
from torch.utils.data import random_split
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])


train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
train_size = 40000
val_size = len(train_dataset) - train_size
train_set, val_set = random_split(train_dataset, [train_size, val_size])
#print(train_size, val_size) #they are 40000 and 10000 respectively.
train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=2)
test_set = torchvision.datasets.CIFAR10(root="./data/", train=False, download=True, transform=transform)
val_loader = DataLoader(val_set, batch_size=batch_size, shuffle=False, num_workers=2)
testloader = DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=2)


Files already downloaded and verified
Files already downloaded and verified


In [110]:
import torch.nn.utils.prune as prune
pruning_ratio = 0.5
model = resnet18(pretrained=False)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 10)
model.load_state_dict(torch.load('./models/modelResNet.pth'))
parameters_to_prune = []


d:\python\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
d:\python\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


In [111]:
module= model.conv1
print(list(module.named_parameters()))

[('weight', Parameter containing:
tensor([[[[ 5.6301e-02, -3.3317e-02, -2.6283e-02,  ...,  7.1762e-03,
           -1.5437e-02, -1.6184e-02],
          [ 5.5005e-02,  1.8621e-02, -3.1146e-02,  ..., -2.0491e-02,
           -1.0332e-02, -4.5827e-02],
          [ 4.3598e-02, -2.7003e-02, -3.2107e-02,  ...,  3.8094e-03,
            4.6784e-02,  1.2251e-02],
          ...,
          [ 3.0689e-02, -2.0697e-02, -5.9207e-02,  ..., -3.2679e-02,
           -4.7373e-02, -1.6765e-02],
          [ 2.9091e-02, -3.9187e-02, -5.1207e-02,  ..., -3.0126e-02,
           -4.9887e-02, -1.8109e-02],
          [ 5.1639e-02,  5.6830e-03, -3.5043e-02,  ...,  7.0827e-03,
           -5.0458e-02, -3.1624e-03]],

         [[ 5.3227e-02,  1.1374e-03, -6.4848e-02,  ...,  1.1745e-02,
           -3.4678e-02, -8.0377e-02],
          [-3.2463e-03, -3.0599e-02, -1.0340e-01,  ..., -1.2938e-02,
           -3.4355e-02, -7.7483e-02],
          [-9.4215e-03, -3.5572e-02, -4.6945e-02,  ..., -2.1222e-02,
           -3.4136e-02, 

In [112]:
print(list(module.named_buffers()))
prune.random_unstructured(module, name="weight", amount=0.3)


[]


Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)

In [113]:
print(list(module.named_parameters()))
print(list(module.named_buffers()))

[('weight_orig', Parameter containing:
tensor([[[[ 5.6301e-02, -3.3317e-02, -2.6283e-02,  ...,  7.1762e-03,
           -1.5437e-02, -1.6184e-02],
          [ 5.5005e-02,  1.8621e-02, -3.1146e-02,  ..., -2.0491e-02,
           -1.0332e-02, -4.5827e-02],
          [ 4.3598e-02, -2.7003e-02, -3.2107e-02,  ...,  3.8094e-03,
            4.6784e-02,  1.2251e-02],
          ...,
          [ 3.0689e-02, -2.0697e-02, -5.9207e-02,  ..., -3.2679e-02,
           -4.7373e-02, -1.6765e-02],
          [ 2.9091e-02, -3.9187e-02, -5.1207e-02,  ..., -3.0126e-02,
           -4.9887e-02, -1.8109e-02],
          [ 5.1639e-02,  5.6830e-03, -3.5043e-02,  ...,  7.0827e-03,
           -5.0458e-02, -3.1624e-03]],

         [[ 5.3227e-02,  1.1374e-03, -6.4848e-02,  ...,  1.1745e-02,
           -3.4678e-02, -8.0377e-02],
          [-3.2463e-03, -3.0599e-02, -1.0340e-01,  ..., -1.2938e-02,
           -3.4355e-02, -7.7483e-02],
          [-9.4215e-03, -3.5572e-02, -4.6945e-02,  ..., -2.1222e-02,
           -3.4136e

In [114]:
print(module.weight)

tensor([[[[ 0.0000e+00, -3.3317e-02, -2.6283e-02,  ...,  0.0000e+00,
           -1.5437e-02, -0.0000e+00],
          [ 5.5005e-02,  1.8621e-02, -3.1146e-02,  ..., -2.0491e-02,
           -1.0332e-02, -0.0000e+00],
          [ 4.3598e-02, -2.7003e-02, -3.2107e-02,  ...,  3.8094e-03,
            4.6784e-02,  1.2251e-02],
          ...,
          [ 0.0000e+00, -0.0000e+00, -0.0000e+00,  ..., -3.2679e-02,
           -4.7373e-02, -0.0000e+00],
          [ 2.9091e-02, -3.9187e-02, -5.1207e-02,  ..., -3.0126e-02,
           -4.9887e-02, -0.0000e+00],
          [ 5.1639e-02,  5.6830e-03, -3.5043e-02,  ...,  0.0000e+00,
           -5.0458e-02, -3.1624e-03]],

         [[ 5.3227e-02,  1.1374e-03, -6.4848e-02,  ...,  1.1745e-02,
           -3.4678e-02, -8.0377e-02],
          [-3.2463e-03, -3.0599e-02, -1.0340e-01,  ..., -0.0000e+00,
           -0.0000e+00, -7.7483e-02],
          [-0.0000e+00, -3.5572e-02, -4.6945e-02,  ..., -0.0000e+00,
           -0.0000e+00, -1.3921e-02],
          ...,
     

In [115]:
print(module._forward_pre_hooks)

OrderedDict([(697, <torch.nn.utils.prune.RandomUnstructured object at 0x000002D94FA6C910>)])


In [116]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 5.6301e-02, -3.3317e-02, -2.6283e-02,  ...,  7.1762e-03,
           -1.5437e-02, -1.6184e-02],
          [ 5.5005e-02,  1.8621e-02, -3.1146e-02,  ..., -2.0491e-02,
           -1.0332e-02, -4.5827e-02],
          [ 4.3598e-02, -2.7003e-02, -3.2107e-02,  ...,  3.8094e-03,
            4.6784e-02,  1.2251e-02],
          ...,
          [ 3.0689e-02, -2.0697e-02, -5.9207e-02,  ..., -3.2679e-02,
           -4.7373e-02, -1.6765e-02],
          [ 2.9091e-02, -3.9187e-02, -5.1207e-02,  ..., -3.0126e-02,
           -4.9887e-02, -1.8109e-02],
          [ 5.1639e-02,  5.6830e-03, -3.5043e-02,  ...,  7.0827e-03,
           -5.0458e-02, -3.1624e-03]],

         [[ 5.3227e-02,  1.1374e-03, -6.4848e-02,  ...,  1.1745e-02,
           -3.4678e-02, -8.0377e-02],
          [-3.2463e-03, -3.0599e-02, -1.0340e-01,  ..., -1.2938e-02,
           -3.4355e-02, -7.7483e-02],
          [-9.4215e-03, -3.5572e-02, -4.6945e-02,  ..., -2.1222e-02,
           -3.4136e

In [117]:
print(model.state_dict().keys())

odict_keys(['conv1.weight_orig', 'conv1.weight_mask', 'bn1.weight', 'bn1.bias', 'bn1.running_mean', 'bn1.running_var', 'bn1.num_batches_tracked', 'layer1.0.conv1.weight', 'layer1.0.bn1.weight', 'layer1.0.bn1.bias', 'layer1.0.bn1.running_mean', 'layer1.0.bn1.running_var', 'layer1.0.bn1.num_batches_tracked', 'layer1.0.conv2.weight', 'layer1.0.bn2.weight', 'layer1.0.bn2.bias', 'layer1.0.bn2.running_mean', 'layer1.0.bn2.running_var', 'layer1.0.bn2.num_batches_tracked', 'layer1.1.conv1.weight', 'layer1.1.bn1.weight', 'layer1.1.bn1.bias', 'layer1.1.bn1.running_mean', 'layer1.1.bn1.running_var', 'layer1.1.bn1.num_batches_tracked', 'layer1.1.conv2.weight', 'layer1.1.bn2.weight', 'layer1.1.bn2.bias', 'layer1.1.bn2.running_mean', 'layer1.1.bn2.running_var', 'layer1.1.bn2.num_batches_tracked', 'layer2.0.conv1.weight', 'layer2.0.bn1.weight', 'layer2.0.bn1.bias', 'layer2.0.bn1.running_mean', 'layer2.0.bn1.running_var', 'layer2.0.bn1.num_batches_tracked', 'layer2.0.conv2.weight', 'layer2.0.bn2.weigh

In [118]:
print(list(module.named_parameters()))

[('weight_orig', Parameter containing:
tensor([[[[ 5.6301e-02, -3.3317e-02, -2.6283e-02,  ...,  7.1762e-03,
           -1.5437e-02, -1.6184e-02],
          [ 5.5005e-02,  1.8621e-02, -3.1146e-02,  ..., -2.0491e-02,
           -1.0332e-02, -4.5827e-02],
          [ 4.3598e-02, -2.7003e-02, -3.2107e-02,  ...,  3.8094e-03,
            4.6784e-02,  1.2251e-02],
          ...,
          [ 3.0689e-02, -2.0697e-02, -5.9207e-02,  ..., -3.2679e-02,
           -4.7373e-02, -1.6765e-02],
          [ 2.9091e-02, -3.9187e-02, -5.1207e-02,  ..., -3.0126e-02,
           -4.9887e-02, -1.8109e-02],
          [ 5.1639e-02,  5.6830e-03, -3.5043e-02,  ...,  7.0827e-03,
           -5.0458e-02, -3.1624e-03]],

         [[ 5.3227e-02,  1.1374e-03, -6.4848e-02,  ...,  1.1745e-02,
           -3.4678e-02, -8.0377e-02],
          [-3.2463e-03, -3.0599e-02, -1.0340e-01,  ..., -1.2938e-02,
           -3.4355e-02, -7.7483e-02],
          [-9.4215e-03, -3.5572e-02, -4.6945e-02,  ..., -2.1222e-02,
           -3.4136e

In [119]:
print(list(module.named_buffers()))

[('weight_mask', tensor([[[[0., 1., 1.,  ..., 0., 1., 0.],
          [1., 1., 1.,  ..., 1., 1., 0.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [0., 0., 0.,  ..., 1., 1., 0.],
          [1., 1., 1.,  ..., 1., 1., 0.],
          [1., 1., 1.,  ..., 0., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 0., 0., 1.],
          [0., 1., 1.,  ..., 0., 0., 1.],
          ...,
          [1., 0., 1.,  ..., 1., 1., 0.],
          [0., 1., 1.,  ..., 1., 1., 1.],
          [0., 1., 0.,  ..., 1., 1., 0.]],

         [[1., 1., 0.,  ..., 1., 1., 1.],
          [1., 0., 1.,  ..., 1., 1., 1.],
          [1., 0., 0.,  ..., 1., 1., 1.],
          ...,
          [1., 0., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 0., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]],


        [[[1., 0., 0.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 0., 0.,  ..., 1., 0., 0.],
          ...,
          [1., 1., 1.,  ..., 0., 

In [120]:
prune.remove(module, 'weight')
print(list(module.named_parameters()))

[('weight', Parameter containing:
tensor([[[[ 0.0000e+00, -3.3317e-02, -2.6283e-02,  ...,  0.0000e+00,
           -1.5437e-02, -0.0000e+00],
          [ 5.5005e-02,  1.8621e-02, -3.1146e-02,  ..., -2.0491e-02,
           -1.0332e-02, -0.0000e+00],
          [ 4.3598e-02, -2.7003e-02, -3.2107e-02,  ...,  3.8094e-03,
            4.6784e-02,  1.2251e-02],
          ...,
          [ 0.0000e+00, -0.0000e+00, -0.0000e+00,  ..., -3.2679e-02,
           -4.7373e-02, -0.0000e+00],
          [ 2.9091e-02, -3.9187e-02, -5.1207e-02,  ..., -3.0126e-02,
           -4.9887e-02, -0.0000e+00],
          [ 5.1639e-02,  5.6830e-03, -3.5043e-02,  ...,  0.0000e+00,
           -5.0458e-02, -3.1624e-03]],

         [[ 5.3227e-02,  1.1374e-03, -6.4848e-02,  ...,  1.1745e-02,
           -3.4678e-02, -8.0377e-02],
          [-3.2463e-03, -3.0599e-02, -1.0340e-01,  ..., -0.0000e+00,
           -0.0000e+00, -7.7483e-02],
          [-0.0000e+00, -3.5572e-02, -4.6945e-02,  ..., -0.0000e+00,
           -0.0000e+00, 

In [121]:

"""#print(list(model.named_modules()))
parameters_to_prune = (
    (model.conv1, 'weight'),
    (model.bn1, 'weight'),
    (model.fc, 'weight'),
)

prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.5,
    )


print(list(model.named_parameters()))
"""


"#print(list(model.named_modules()))\nparameters_to_prune = (\n    (model.conv1, 'weight'),\n    (model.bn1, 'weight'),\n    (model.fc, 'weight'),\n)\n\nprune.global_unstructured(\n    parameters_to_prune,\n    pruning_method=prune.L1Unstructured,\n    amount=0.5,\n    )\n\n\nprint(list(model.named_parameters()))\n"

In [122]:
import torch.nn.utils.prune as prune
pruning_ratio = 0.5
model = resnet18(pretrained=False)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 10)
model.load_state_dict(torch.load('./models/modelResNet.pth'))

<All keys matched successfully>

In [123]:
parameters_to_prune = (
    (model.conv1, 'weight'),
    (model.fc, 'weight'),
    (model.bn1, 'weight'),

)

prune.global_unstructured(
    parameters_to_prune,
    pruning_method=prune.L1Unstructured,
    amount=0.5,
)

In [124]:
print(
    "Sparsity in conv1.weight: {:.2f}%".format(
        100. * float(torch.sum(model.conv1.weight == 0))
        / float(model.conv1.weight.nelement())
    )
)
print(
    "Sparsity in fc.weight: {:.2f}%".format(
        100. * float(torch.sum(model.fc.weight == 0))
        / float(model.fc.weight.nelement())
    )
)
print(
    "Sparsity in bn1.weight: {:.2f}%".format(
        100. * float(torch.sum(model.bn1.weight == 0))
        / float(model.bn1.weight.nelement())
    )
)
print(list(module.named_parameters()))

Sparsity in conv1.weight: 50.80%
Sparsity in fc.weight: 49.16%
Sparsity in bn1.weight: 0.00%
[('weight', Parameter containing:
tensor([[[[ 0.0000e+00, -3.3317e-02, -2.6283e-02,  ...,  0.0000e+00,
           -1.5437e-02, -0.0000e+00],
          [ 5.5005e-02,  1.8621e-02, -3.1146e-02,  ..., -2.0491e-02,
           -1.0332e-02, -0.0000e+00],
          [ 4.3598e-02, -2.7003e-02, -3.2107e-02,  ...,  3.8094e-03,
            4.6784e-02,  1.2251e-02],
          ...,
          [ 0.0000e+00, -0.0000e+00, -0.0000e+00,  ..., -3.2679e-02,
           -4.7373e-02, -0.0000e+00],
          [ 2.9091e-02, -3.9187e-02, -5.1207e-02,  ..., -3.0126e-02,
           -4.9887e-02, -0.0000e+00],
          [ 5.1639e-02,  5.6830e-03, -3.5043e-02,  ...,  0.0000e+00,
           -5.0458e-02, -3.1624e-03]],

         [[ 5.3227e-02,  1.1374e-03, -6.4848e-02,  ...,  1.1745e-02,
           -3.4678e-02, -8.0377e-02],
          [-3.2463e-03, -3.0599e-02, -1.0340e-01,  ..., -0.0000e+00,
           -0.0000e+00, -7.7483e-02],


In [125]:
prune.remove(model.bn1, 'weight')
prune.remove(model.conv1, 'weight')
prune.remove(model.fc, 'weight')


[('', ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=Tr

In [127]:
print(list(model.named_parameters()))

[('conv1.weight', Parameter containing:
tensor([[[[ 0.0563, -0.0000, -0.0000,  ...,  0.0000, -0.0000, -0.0000],
          [ 0.0550,  0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0458],
          [ 0.0436, -0.0000, -0.0000,  ...,  0.0000,  0.0468,  0.0000],
          ...,
          [ 0.0000, -0.0000, -0.0592,  ..., -0.0000, -0.0474, -0.0000],
          [ 0.0000, -0.0392, -0.0512,  ..., -0.0000, -0.0499, -0.0000],
          [ 0.0516,  0.0000, -0.0000,  ...,  0.0000, -0.0505, -0.0000]],

         [[ 0.0532,  0.0000, -0.0648,  ...,  0.0000, -0.0000, -0.0804],
          [-0.0000, -0.0000, -0.1034,  ..., -0.0000, -0.0000, -0.0775],
          [-0.0000, -0.0000, -0.0469,  ..., -0.0000, -0.0000, -0.0000],
          ...,
          [ 0.0723,  0.0000, -0.0000,  ...,  0.0000,  0.0467,  0.0000],
          [ 0.0610,  0.0000, -0.0802,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0950,  0.0494,  0.0000,  ...,  0.0501, -0.0000,  0.0000]],

         [[ 0.0507, -0.0000, -0.0409,  ..., -0.0000, -0.0000, 

In [128]:
print(model.state_dict().keys())

odict_keys(['conv1.weight', 'bn1.bias', 'bn1.weight', 'bn1.running_mean', 'bn1.running_var', 'bn1.num_batches_tracked', 'layer1.0.conv1.weight', 'layer1.0.bn1.weight', 'layer1.0.bn1.bias', 'layer1.0.bn1.running_mean', 'layer1.0.bn1.running_var', 'layer1.0.bn1.num_batches_tracked', 'layer1.0.conv2.weight', 'layer1.0.bn2.weight', 'layer1.0.bn2.bias', 'layer1.0.bn2.running_mean', 'layer1.0.bn2.running_var', 'layer1.0.bn2.num_batches_tracked', 'layer1.1.conv1.weight', 'layer1.1.bn1.weight', 'layer1.1.bn1.bias', 'layer1.1.bn1.running_mean', 'layer1.1.bn1.running_var', 'layer1.1.bn1.num_batches_tracked', 'layer1.1.conv2.weight', 'layer1.1.bn2.weight', 'layer1.1.bn2.bias', 'layer1.1.bn2.running_mean', 'layer1.1.bn2.running_var', 'layer1.1.bn2.num_batches_tracked', 'layer2.0.conv1.weight', 'layer2.0.bn1.weight', 'layer2.0.bn1.bias', 'layer2.0.bn1.running_mean', 'layer2.0.bn1.running_var', 'layer2.0.bn1.num_batches_tracked', 'layer2.0.conv2.weight', 'layer2.0.bn2.weight', 'layer2.0.bn2.bias', '